version: "2.1"
services:
  phets-users-ms:
    container_name: phets-users-ms
    build: .
    ports:
      - "4006:4006"
    environment:
      LDAP_IP: 172.17.0.1
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3006/user?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: phets-user
      SPRING_DATASOURCE_PASSWORD: phets-password
    depends_on:
      phets-users-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I phets-users-ms:4006/user --fail"
      interval: 20s
      retries: 10
  phets-users-db:
    image: mysql:5.7
    container_name: phets-users-db
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    volumes:
      - phets-users-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ph375-u53r5
      MYSQL_DATABASE: user
      MYSQL_USER: phets-user
      MYSQL_PASSWORD: phets-password
    ports:
      - "3006:3306"

volumes:
  phets-users-db: